### ISSUE TITLE
Accounts with multiple keys don't work properly.

### ISSUE THREAD

**Issue by tcpolymath** [MattyIce/steem-keychain#122]
When I add a second posting key to an account I can't add that key to Keychain while the original key exists. If I delete the original key then I can import the posting key individually but I can no longer import any keys with the master password. 

This basically makes Keychain not a viable method for accounts being used by multiple users each with their own keys.

Related a little bit to https://github.com/MattyIce/steem-keychain/issues/109

**Comment by shawnpringle** [comment]
I have come to understand why this is so.  In accounts.js when keys are imported the entered or derived WIF is used to obtain a public key.  This public key is only checked against the first key for cases of both active and posting.  This problem does not apply to the owner key and memo key because the owner key is never used by KeyChain and there can only be one memo key per account.

**Comment by shawnpringle** [comment]
The following fixes this issue https://github.com/MattyIce/steem-keychain/pull/125
