### ISSUE TITLE
Ability to check who's signed in

### ISSUE THREAD

**Issue by quochuy** [MattyIce/steem-keychain#38]
I have a tool which I would restrict to certain steem users. Would be good if I can interrogate steem keychain to see who is currently signed into the extension. Alternatively, the website could send a username and steem keychain would respond with true or false depending if that user is signed in with steem keychain.

**Comment by MattyIce** [comment]
@quochuy actually we purposely did not add this feature in because it's a security/privacy issue. Many people may not want others to know which accounts they own or have access to. If a site could query this information from steem keychain that would be a problem.

I think you can achieve what you want by using the "decode" function though. You can encrypt a message using one of the public keys of an account and request that the keychain extension decode it using the corresponding private key. The user can choose whether or not to allow that transaction, and if they allow it then you know that they have access to that private key for that account and can allow/restrict them from using your tool accordingly.
