### ISSUE TITLE
Password Requirements

### ISSUE THREAD

**Issue by selabie68** [MattyIce/steem-keychain#65]
For example look at the Steem keys. The resulting keys only have Alpha-Numeric characters and are still considered secure.

Users should have the ability to select a password they can remember without restrictions on the types of characters they have to use.

`Your password must be at least 8 characters long and include a lowercase letter, an uppercase letter, a digit, and a special character.`

Relevant: https://xkcd.com/936/

**Comment by roelandp** [comment]
@selabie68 

Since the wallet stores the private key(s) of the user when using the app, and those private key(s) will give access to funds it is common practise to educate users in the importance of these private keys. Choosing a simple password will lead to easy guessing of the password through automated machines. If an attacker finds a loophole and knows that the service' password requirements are very lax, it is interesting to try and obtain wallet files to brute-force attack passwords against the wallet file. 

FYI Steem keys have a length of 51 characters. According to the dropbox opensource zxcvbn library (which is a helper for devs to analyse password strength and give hints) cracking a 51 charlength with  (offline attack, fast hash, many cores), will take centuries. Here you can test the zxcvbn library yourself (also contains some demo's). It mixes passwordlists with analyses password char sequences and more smartness. 

It would be cool to see if fingerprint unlock is allowed with chrome / safari and other browsers (Web Authentication API) so users could use those advanced secure authtentication methods, like TouchId or a Yubi key.

**Comment by Transisto** [comment]
I agree that the password are too stringent. A user would need physical access to the device to even have a chance at guessing password. 

I've tried to test Keychain 3 times and forgot my password every-times.

Most people when asked for a password 8 characters long and include a lowercase letter, an uppercase letter, a digit, and a special character. Will end up chosing "Ab-12345" or one of the few other variant of minimum requirement maximum simplicity which completely defeat the original intent.

**Comment by roelandp** [comment]
secure passwords are still very important. who knows if a flaw or malicious other plugin offloads the wallet file. 

that said I recommend maybe consider using for example the excellent zxcvbn password strength validator which still enables you to require strong pwds from ur users while also enabling long unguessable string (phrase) based passwords like “correct horse battery staple” :) https://xkcd.com/936/

and educate people about password managers :)
