### ISSUE TITLE
Keychain does not auto-lock when idle

### ISSUE THREAD

**Issue by themarkymark-steem** [MattyIce/steem-keychain#67]
Chrome (latest)
Windows 10 Pro x64

When certain websites are loaded that have interactions (like Magic Dice), Keychain does not properly auto-lock.  Other extensions like 1Password lock successfully.

**Comment by stoodkev** [comment]
The extension auto-lock when it is idle for a certain time , ie. if it s not doing anything, if Magic Dice is interacting with it, it is not idle, and won't autolock, this is by design.

**Comment by stoodkev** [comment]
Okay I got it wrong at first but after testing I get what you mean, this is due to the fact Keychain will inject its functions in every new page, so if you navigate on your browser, it won't be consider as idle. 
The solution would be to build ourselves an auto-lock rather than using the chrome `onStateChanged`.
Any thought about that, @MattyIce ?

**Comment by thecryptodrive** [comment]
@stoodkev @MattyIce I also have this issue, it doesn't autolock and I can use keychain without password a few hours later. My active key is in there so it's a bit of a concern.
